services:
  - type: web
    name: ugp-pld-copilot-api
    env: docker
    rootDir: .
    dockerfilePath: ./backend/Dockerfile
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: API_RATE_LIMIT
        value: "20"
      - key: FRONTEND_URL
        value: https://frontend-aads19s-projects.vercel.app
      - key: CHROMA_COLLECTION_NAME
        value: pvd_docs
      - key: CHROMA_PATH
        value: /var/data/chroma_store
      - key: DATABASE_PATH
        value: /var/data/conversations.db
